// Localhost ---------------------------------------------------------------
// Localhost ---------------------------------------------------------------
// Localhost ---------------------------------------------------------------

### Create a reviews
POST http://localhost:3000/api/reviews HTTP/1.1
content-type: application/json

{
   "productId": "68534f39767c0fba49141349",
   "userId": "68534f39767c0fba49141349",
   "rating": 5,
   "comment": 
   "Their work is always top-notch. This vase is a perfect centerpiece for my dining table. The quality is outstanding!"
}

### Get all reviews
GET http://localhost:3000/api/reviews HTTP/1.1

### Get review by id
GET http://localhost:3000/api/reviews/6853a32814423edb4f5c4894 HTTP/1.1

### Get review by product id
GET http://localhost:3000/api/reviews/product/68536925c02ba3fb8e0a6a00 HTTP/1.1

### Get review by user id
GET http://localhost:3000/api/reviews/user/684a69c11e10087f3121bd36 HTTP/1.1


### Update a review
PUT http://localhost:3000/api/reviews/68534f39767c0fba49141349 HTTP/1.1
content-type: application/json

{
   "productId": "68534f39767c0fba49141349",
   "userId": "68534f39767c0fba49141349",
   "rating": 5,
   "comment": 
   "Their work is always top-notch. This vase is a perfect centerpiece for my dining table. The quality is outstanding!"
}

### Delete a review
DELETE http://localhost:3000/api/reviews/68534f39767c0fba49141349 HTTP/1.1

// Production ---------------------------------------------------------------
// Production ---------------------------------------------------------------
// Production ---------------------------------------------------------------

### Create a reviews
POST https://handcrafted-haven-mozartsoares-projects.vercel.app/api/reviews HTTP/1.1
content-type: application/json

{
   "productId": "68534f39767c0fba49141349",
   "userId": "68534f39767c0fba49141349",
   "rating": 5,
   "comment": 
   "Their work is always top-notch. This vase is a perfect centerpiece for my dining table. The quality is outstanding!"
}

### Get all reviews
GET https://handcrafted-haven-mozartsoares-projects.vercel.app/api/reviews HTTP/1.1

### Get review by id
GET https://handcrafted-haven-mozartsoares-projects.vercel.app/api/reviews/6853a32814423edb4f5c4894 HTTP/1.1

### Get review by product id
GET https://handcrafted-haven-mozartsoares-projects.vercel.app/api/reviews/product/68536925c02ba3fb8e0a6a00 HTTP/1.1

### Get review by user id
GET https://handcrafted-haven-mozartsoares-projects.vercel.app/api/reviews/user/684a69c11e10087f3121bd36 HTTP/1.1


### Update a review
PUT https://handcrafted-haven-mozartsoares-projects.vercel.app/api/reviews/68534f39767c0fba49141349 HTTP/1.1
content-type: application/json

{
   "productId": "68534f39767c0fba49141349",
   "userId": "68534f39767c0fba49141349",
   "rating": 5,
   "comment": 
   "Their work is always top-notch. This vase is a perfect centerpiece for my dining table. The quality is outstanding!"
}

### Delete a review
DELETE https://handcrafted-haven-mozartsoares-projects.vercel.app/api/reviews/68534f39767c0fba49141349 HTTP/1.1